name: CI 

on: 
 push:
 workflow_dispatch:


permissions:
  contents: read

jobs:
 secret_scanning:
   name: run gitleaks
   runs-on: ubuntu-latest

   steps:
     - name: checkout code
       uses: actions/checkout@v6
       with:
          fetch-depth: 0
     
     - name: run gitleaks
       uses: gitleaks/gitleaks-action@v3
       env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

       
 sast_scan:
   name: Run Bandit scan
   runs-on: ubuntu-latest
   
   steps:
     - name: checkout our code
       uses: actions/checkout@v5

     - name: install python
       uses: actions/setup-python@v7.0.0
       with:
        python-version: 3.8

     - name: installing Bandit
       run: pip install Bandit
     
     - name: running bandit scan
       run: bandit -lll -ii -r . -f json -o bandit-report.json # -r scans current directory, -lll ignores medium and low severity
       
     - name: upload artifcacts to save json
       uses: actions/upload-artifact@v7.0.1
       if: always()
       with: 
        name: bandit-findings
        path: bandit-report.json
   
