name: CI 

on: push

jobs:
 sast_scan:
   name: Run Bandit scan
   runs-on: ubuntu-latest
   
   steps:
     - name: checkout our code
       uses: actions/checkout@v2

     - name: install python
       uses: actions/setup-python@v7.0.0
       with:
        python-version: 3.8

     - name: installing Bandit
       run: pip install Bandit
     
     - name: running bandit scan
       run: bandit -lll -ii -r . -f json -o bandit-report.json # -r scans current directory, -lll ignores medium and low severity
       
     - name: upload artifcacts to save json
       uses: actions/upload-artifact@v3
       if: always()
       with: 
        name: bandit-findings
        path: bandit-report.json
   
